def image

pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                script {
                    image = docker.build("rhofman14/maven-agent:3.8.6-jdk11", "--pull -f jenkins/Dockerfile_agent jenkins")
                }
            }
        }
        stage('Smoke Test') {
            steps {
                script {
                    container = image.run()
                    container.stop()
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    withDockerRegistry([credentialsId: "docker-hub", url: "" ]) {
                        image.push()
                    }
                }
            }
        }
    }
}
